- .gitignore
- ios/Runner/Info.plist
- lib/i18n/app_de.json
- lib/i18n/app_en.json
- lib/main.dart
- pubspec.lock
- pubspec.yaml
- slang.yaml
> 252: Setup slang

- .github/hooks/pre-commit
- .idea/codeStyles/Project.xml
- .idea/codeStyles/codeStyleConfig.xml
- analysis_options.yaml
- lib/main.dart
- package.json
> 251: Linting formatting and typechecking

- lib/features/news/screens/news_detail_screen.dart
- lib/features/news/widgets/news_card.dart
Hide bookmarks until implemented.
Users might wonder why this is not visible anymore.
Have a look at news cards and news details.
Fixes: #567 
---
> 567: Hide bookmarks until implemented

- .vscode/settings.json
- lib/app/geocode/nominatim.dart
- lib/app/services/converters.dart
- lib/app/services/converters/focus_area_parsing.dart
- lib/app/services/converters/lat_lng_parsing.dart
- lib/app/services/converters/place_parser.dart
- lib/app/services/converters/string_extension.dart
- lib/app/services/nominatim_service.dart
- lib/features/campaigns/helper/campaign_constants.dart
- lib/features/campaigns/helper/campaign_session_settings.dart
- lib/features/campaigns/screens/doors_screen.dart
- lib/features/campaigns/screens/flyer_screen.dart
- lib/features/campaigns/screens/map_consumer.dart
- lib/features/campaigns/screens/mixins.dart
- lib/features/campaigns/screens/mixins/search_mixin.dart
- lib/features/campaigns/screens/posters_screen.dart
- lib/features/campaigns/widgets/map_container.dart
- lib/features/campaigns/widgets/map_controller.dart
- lib/i18n/app_de.json
- lib/main.dart
- use nominatim for address search
- sort items by distance instead of "relevance"
- show "no items found"
- put a collapse action in the search bar (to overlay the compass and to have an action for collapsing)
- only streets and cities/towns can be searched
-
-
-
-
Fixes: #216 
---
> 216: make map searchable

- lib/app/auth/bloc/auth_bloc.dart
- lib/app/auth/repository/auth_repository.dart
- lib/features/login/widgets/welcome_view.dart
- lib/features/settings/screens/settings_screen.dart
Rename signIn/signOut to login/logout to streamline naming.
- Rename signIn to login
- Rename signOut to logout
N/A
N/A
Fixes: N/A
---
> Fix login naming

- lib/app/auth/repository/auth_repository.dart
- lib/app/constants/config.dart
- lib/app/services/access_token_authenticator.dart
- lib/app/services/gruene_api_core.dart
- lib/app/services/interceptors/auth_interceptor.dart
- lib/app/services/interceptors/keep_alive_interceptor.dart
- lib/app/services/interceptors/user_agent_interceptor.dart
- lib/app/utils/logger.dart
- lib/app/utils/open_url.dart
Refactor api core by splitting it up in separate files and improve logging.
_This PR consists of changes done while investigating the deletion of login credentials when opening 2fa. Since I think these changes make sense, I created a PR now._
- Extract api core code for auth interceptor, keep alive interceptor, user agent interceptor and access token authenticator to separate files 
- Simplify api core logic in a few places (especially access token/authenticator logic)
- Use a common logging and at additional debug log statements
N/A
Test that everything related to the api and authenticating requests still works
Fixes: N/A
---
> Refactor api core and improve logging

- .circleci/config.yml
- .circleci/src/jobs/build_android.yml
- android/fastlane/Fastfile
- android/fastlane/README.md
- ios/fastlane/Appfile
- ios/fastlane/Deliverfile
- ios/fastlane/Fastfile
Fix ios releases and tidy up a little.
- Set default release notes for iOS
- Clean up a few todos and comments
N/A
N/A
Fixes: #566
---
> 566: Fix ios releases and tidy up a little

- .vscode/settings.json
- lib/features/campaigns/screens/statistics_screen.dart
just fix the formatting
-
-
-
-
Fixes: #588 
---
> 588 fix number formatting in statistics

- lib/features/news/models/news_model.dart
- lib/features/news/screens/news_detail_screen.dart
- lib/features/news/utils/utils.dart
- lib/features/news/widgets/news_card.dart
- lib/features/profiles/screens/own_profile_screen.dart
* fixes an uncaught error on profiles screen, when user has no memberships
* displays real images for news instead of placeholders
> Bugfix Profiles and News

- lib/features/news/models/news_model.dart
- lib/features/news/screens/news_detail_screen.dart
- lib/features/news/utils/utils.dart
- lib/features/news/widgets/news_card.dart
- pubspec.lock
- pubspec.yaml
> Draft: 211 Enhance News Perfromance

- lib/app/widgets/bottom_navigation.dart
Fix blank 2fa screen from login screen.
- Avoid empty bottom navigation to fill whole screen
N/A
Go to login screen and navigate to 2fa screen.
Fixes: #599
---
> 599: Fix blank 2fa screen

- lib/i18n/app_de.json
> 606: fix typo

- lib/app/services/converters/campaign_action_parsing.dart
- lib/app/services/converters/date_time_parsing.dart
- lib/app/services/gruene_api_campaigns_service.dart
- lib/app/services/gruene_api_door_service.dart
- lib/app/services/gruene_api_flyer_service.dart
- lib/app/services/gruene_api_poster_service.dart
- lib/app/widgets/app_bar.dart
- lib/features/campaigns/helper/campaign_action_cache.dart
- lib/i18n/app_de.json
- encapsulate api calls in error handler
- detect 404 on update/delete and remove item from cache
- continue on sync-error to process the rest of the cache
- allow storing cache as Json and to send it to devs
-
-
Fixes: #604 
---
> 604: fix possible cache collisions

- .circleci/config.yml
- .circleci/src/commands/install_flutter.yml
- tools/trigger-pipeline.ts
Fix iOS CI and fix trigger pipeline script.
- Fix iOS CI by using `shasum -a 256` instead of `sha256sum`
- Fix trigger pipeline script by fixing repo name
- N/A
N/A, hope that the CI succeeds :crossed_fingers: 
Fixes: N/A
---
> Fix iOS CI and trigger pipeline script

- .env.prod
- lib/app/constants/config.dart
- lib/app/services/gruene_api_campaigns_service.dart
- lib/app/services/gruene_api_poster_service.dart
POIs should only be visible when they are younger than a certain date.
-
-
Fixes: #632 
---
> 632: filter pois by a specific cut-off date

- lib/i18n/app_de.json
> 638: remove campaign subtitle

- lib/app/services/gruene_api_core.dart
- lib/features/news/bloc/bookmark_bloc.dart
- lib/features/news/bloc/bookmark_event.dart
- lib/features/news/bloc/bookmark_state.dart
- lib/features/news/domain/bookmark_service.dart
- lib/features/news/domain/news_api_service.dart
- lib/features/news/screens/news_detail_screen.dart
- lib/features/news/screens/news_screen.dart
- lib/features/news/widgets/bookmark_button.dart
- lib/features/news/widgets/news_card.dart
- lib/main.dart
- swaggers/gruene-api.yaml
Allow users to bookmark news articles.
- Adds bookmark toggle to news cards in list view and to news article detail screen
- Adds tab navigation to news screen to switch between latest news and bookmarked news
None
- Navigate to news page
- Bookmark some news
- Navigate to tab "Gespeichert" to see bookmarked news articles
Fixes: #213
---
> 213 articles bookmarks

- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/Info.plist
- ios/Runner/RunnerDebug.entitlements
- ios/Runner/RunnerRelease.entitlements
- lib/app/services/fcm_notification_service.dart
- version.yaml
https://stackoverflow.com/questions/77089496/flutter-apns-token-has-not-been-set-yet-please-ensure-the-apns-token-is-avail
Updated Xcode project settings like described in the stackoverflow thread:
* addCapabilities Background Modes (all)
* Background fetch
* Remote notifications
* addCapabilities Push notifications (all)
Commited all changes made by Xcode
> Fix iOS Push Notifications

- README.md
- docs/release-workflow.md
Add release workflow documentation.
N/A
N/A
Fixes: N/A
---
> Add release workflow documentation

- android/app/src/debug/google-services.json
Adds a  `google-services.json` for debug mode.
> 145: Add `google-services.json` For Debug mode

- lib/i18n/app_de.json
Rename logout label `Ausloggen` to `Abmelden`.
N/A
Navigate to settings and scroll down.
Fixes: #652
---
> 652: Rename logout

- lib/features/settings/screens/settings_screen.dart
- lib/i18n/app_de.json
Remove accessibility from settings and translations.
N/A
Open the settings and see that the accessibility item is removed.
Fixes: #222
---
> 222: Remove accessibility from settings

- ios/Podfile.lock
- lib/app/auth/repository/auth_repository.dart
- lib/app/utils/utils.dart
- lib/features/login/screens/login_screen.dart
- pubspec.lock
- pubspec.yaml
Show error screen if offline on login screen (either because not logged in or because the access token expired).
- Show error screen if offline and on the login screen
- Add [internet_connection_checker_plus](https://pub.dev/packages/internet_connection_checker_plus) 
N/A
0. Replace https://github.com/verdigado/gruene-app/blob/635806119fadc83b7a84c95fd0aeb61fe3f9f934/lib/app/auth/bloc/auth_bloc.dart#L48 with
```dart
final isValid = false;
```
(or delete the access token)
1. Go offline
2. Close the app
3. Reopen the app 
4. See the offline error screen
5. Connect to the internet again
6. Click retry
7. See news screen
Fixes: #625
---
> 625: Show error screen if offline on login screen

- .circleci/config.yml
- .circleci/src/jobs/deliver_android.yml
- .circleci/src/jobs/deliver_ios.yml
- .circleci/src/jobs/notify_promotion.yml
- .circleci/src/jobs/notify_release.yml
- .circleci/src/jobs/promote_android.yml
- .circleci/src/jobs/promote_ios.yml
- .circleci/src/workflows/beta_delivery.yml
- .circleci/src/workflows/production_delivery.yml
- .circleci/src/workflows/promotion.yml
- .github/release.yml
- tools/constants.ts
- tools/git-version.ts
- tools/github-promote-release.ts
- tools/github-release.ts
- tools/package-lock.json
Automatically generate github release notes.
- Add a release note template for automatic release notes with two categories features/fixes/enhancements and maintenance
- Automatically generate release notes in CI
- Only create a single github release (and tag) for both android and ios
- Remove pre_release flag from all past github releases on promotion
- Fix security vulnerabilities in js dependencies
Hopefully none.
N/A
Fixes: N/A
---
> Automatically generate github release notes

- lib/features/campaigns/screens/poster_add_screen.dart
dialog box was shown but result not processed 🫤 
-
-
Fixes: #687 
---
> 687: FIX dialog box not clickable

- lib/app/services/converters.dart
- lib/app/services/converters/date_time_parsing.dart
- lib/app/services/converters/point_converter.dart
- lib/app/services/converters/route_parsing.dart
- lib/app/services/gruene_api_base_service.dart
- lib/app/services/gruene_api_campaigns_base_service.dart
- lib/app/services/gruene_api_door_service.dart
- lib/app/services/gruene_api_flyer_service.dart
- lib/app/services/gruene_api_poster_service.dart
- lib/app/services/gruene_api_route_service.dart
- lib/features/campaigns/helper/campaign_action_cache.dart
- lib/features/campaigns/helper/campaign_constants.dart
- lib/features/campaigns/helper/map_helper.dart
- lib/features/campaigns/screens/flyer_screen.dart
- lib/features/campaigns/screens/map_consumer.dart
- lib/features/campaigns/widgets/map_container.dart
- lib/i18n/de.json
- lib/main.dart
clicking on a route will show a bottom sheet
Additional:
- refactor some parts of CampaignService 
-
-
Fixes: #676 
---
> 676 route bottom sheet

- lib/app/theme/theme.dart
- lib/features/campaigns/helper/media_helper.dart
- lib/features/campaigns/helper/picture_gallery_view.dart
- lib/features/campaigns/screens/flyer_add_screen.dart
- lib/features/campaigns/screens/map_consumer.dart
- lib/features/campaigns/screens/mixins/info_box.dart
- lib/features/campaigns/screens/mixins/search_mixin.dart
- lib/features/campaigns/screens/poster_add_screen.dart
- lib/features/campaigns/widgets/attribution_dialog.dart
- lib/features/campaigns/widgets/close_edit_widget.dart
- lib/features/campaigns/widgets/close_save_widget.dart
- lib/features/campaigns/widgets/enhanced_wheel_slider.dart
- lib/features/campaigns/widgets/location_button.dart
- lib/features/campaigns/widgets/map_container.dart
- lib/features/campaigns/widgets/refresh_button.dart
> 673: update icons according to icon lib
